version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API S3 совместимого хранилища
      - "9001:9001"  # Веб-консоль MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    entrypoint: [ "minio", "server", "/data", "--console-address", ":9001" ]

volumes:
  minio-data:
